apiVersion: v1
kind: Pod
metadata:
  name: netology-web
  labels:
    nw: netweb
spec:
  containers:
  - name: echo
    image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
    ports:
    - containerPort: 8080